name: ideas
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.0
  freezed_annotation: ^0.14.2
  json_serializable: ^4.1.4
  http: ^0.13.3
  connectivity: ^3.0.6
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  auto_route: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  mocktail: ^0.1.4
  dart_code_metrics: ^4.1.0
  flutter_lints: ^1.0.4
  auto_route_generator: ^2.1.0

flutter:
  uses-material-design: true
